<Project>
  <ItemGroup>
    <PackageVersion Include="AngleSharp" Version="1.5.2" />
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageVersion Include="JustEat.HttpClientInterception" Version="5.1.4" />
    <PackageVersion Include="MartinCostello.Logging.XUnit" Version="0.7.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="11.0.0-preview.6.26359.118" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="11.0.0-preview.6.26359.118" />
    <PackageVersion Include="Microsoft.IdentityModel.Protocols" Version="8.19.1" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
  </ItemGroup>
</Project>
