using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;

namespace AspNet.Security.OpenId.Events
{
    public class OpenIdRedirectContext : PropertiesContext<OpenIdAuthenticationOptions>
    {
        public OpenIdRedirectContext(HttpContext context,
            AuthenticationScheme scheme,
            OpenIdAuthenticationOptions options,
            AuthenticationProperties properties, OpenIdAuthenticationMessage message)
            : base(context, scheme, options, properties)
        {
            ProtocolMessage = message;
        }

        /// <summary>
        /// Gets the protocol message that has been generated by the handler up to this point.
        /// </summary>
        public OpenIdAuthenticationMessage ProtocolMessage { get; set; }

        /// <summary>
        /// If true, will skip any default logic for this redirect.
        /// </summary>
        public bool Handled { get; private set; }

        /// <summary>
        /// Skips any default logic for this redirect.
        /// </summary>
        public void HandleResponse() => Handled = true;
    }
}
